### ISSUE TITLE
segmentation fault in video_annotator

### ISSUE THREAD

**Issue by lbugnon** [cvisionai/Tator-Native#95]
It throw "segmentation fault" at the first second of running the video_annotator. I downloaded the lattest src and I followed the build instructions for Ubuntu

**Comment by BGWoodward** [comment]
Hi Leandro, 

Can you please provide a few more system details, such as what version of Ubuntu you are running. It is possible this is caused by a missing library dependency. Also, would it be possible to get the full error trace if you start it from a terminal window?

Thanks,

-Ben
